<h1 style="color:#EE3377">
     Robotics Homogeneous Coordinates Demospace for Class
</h1>



## Jennifer Kay <br> kay@rowan.edu <br> Rowan University Computer Science Department

Last update: 2022-10-18
<p>&nbsp;</p>
<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img align="left" alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br /><p></p>This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.

<ul>



### Important Note Regarding Reuse of this Work: 
* This work **MAY NOT** be shared on commercial websites that charge users for content. 
* So, for example, it would be a breach of this license to post this (or anything derived from it) on chegg.com 
* Please see: http://creativecommons.org/licenses/by-nc-sa/4.0/  for the nitty gritty details 
</ul>


# Getting started: Step 1

*   When you run the code block immediately following this text block titled "Initialization 1"
  * It will produce a huge amount of output. You can ignore virtually all of it.
  * You will know it has finished running because you will see a little check-box to the left of the run icon and also you'll see a message from me reminding you that you may have to restart the runtime


    
#<font color='green'>NOW DO THIS:</font>
* <font color = 'green'>**Run the code block immediately following this text block titled "Initialization 1"** </font>
* <font color = 'green'>**Restart the runtime** 
  * <font color = 'green'>Runtime menu -> Restart runtime 
  * <font color = 'green'>(It doesn't hurt to do it again even if you don't need to)
  * <font color = 'green'>(You have to acknowledge that you really want to do this, and variables may be deleted ... that's really OK!)
* **Run the "Initialization 1 code block a second time!** </font>


In [ ]:
#@title Initialization 1 

import datetime

##########################################################
# Printing a success message so reader feels good
# 
# Also a little bit of a datetime demo

def successMessage(thingToSay="", closer = ""):
  rightNow = datetime.datetime.now()
  rightNowString = rightNow.strftime("%Y-%m-%d %H:%M:%S") 
  stars = stars = "*"*100+"\n"

  header = footer = stars + stars
  line1 = "\n\t\t" + thingToSay + "\n"
  line2 = "\t\t\t"
  line2 += "Finished at " if closer=="" else closer
  line2 += rightNowString + "\n\n"
  
  message = header + line1 + line2 + footer

  print(message)



!pip install ipympl --quiet
!pip install requests --quiet



successMessage ("----> If this is your first time running this code in this session then go to <----\n\t\t----> the Runtime menu and click 'restart runtime' and then run it again!! <-----")




****************************************************************************************************
****************************************************************************************************

		----> If this is your first time running this code in this session then go to <----
		----> the Runtime menu and click 'restart runtime' and then run it again!! <-----
			Finished at 2022-10-25 18:13:20

****************************************************************************************************
****************************************************************************************************



# Getting Started: Step 2

The "Initialization 2" Code below: 
* Just does some 
 imports and customizations for numpy, matplotlib, and sympy
* You shouldn't need to restart the runtime again

#<font color='green'>NOW DO THIS:</font>
* <font color = 'green'>**Run the code block immediately following this text block titled "Initialization 2"** </font>



In [ ]:
#@title Initialization 2


#####################################################
# General Imports and numpy / matplotlib / sympy   setup

#allow support for 3rd party widgets (the matplotlib interactive stuff)
from google.colab import output
output.enable_custom_widget_manager()

#you can disable the above by:
#   from google.colab import output
#   output.enable_custom_widget_manager()

#display live figures in the notebook
%matplotlib ipympl 


#stack overflow says calling a second time may prevent some graphics errors
#%matplotlib notebook 

import matplotlib.pyplot as plt
import numpy as np
import sympy as sp
import math

import requests

# ------------ copy file from url to local runtime environment ------------------- 
def copyFileToRuntime(url, filename):
  r = requests.get(url)
  with open(filename, 'w') as f:
    f.write(r.text)

# Add Dr. Kay's files to colab working directory
url = "https://raw.githubusercontent.com/jenniferskay/kinematics-problems-01/master/pythonFiles/"
filename = "kayHomogeneousTransformations.py"
copyFileToRuntime(url+filename, filename)

filename = "kayHomogeneousTransformGraphics.py"
copyFileToRuntime(url+filename, filename)

filename = "kayColorPalette.py"
copyFileToRuntime(url+filename, filename)


# set all numpy prints to just 3 decimal places
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})   

# import the code that Dr. Kay wrote
import kayHomogeneousTransformations as ht
import kayHomogeneousTransformGraphics as hg
import kayColorPalette as cp






<img src = "https://raw.githubusercontent.com/jenniferskay/kinematics-problems-01/master/graphics/fig02c.jpg">
<!-- <img src = "graphics/fig02c.jpg"> -->


In [9]:
# Note that I'm declaring all of the variables outside of functions so they will be global. 
# Yes, global variables are often evil, but in the case of Jupyter notebooks, we need to keep
# them global so that we can reuse them in future cells.

# F from w to r
print ("(Frame Transform) F from w to r is Trans (10, 0, 0) which is the following 4x4 matrix:" )
frame_transform_w_r = ht.doTrans(10,0,0)
print(frame_transform_w_r)
print() # add a blank line to make it more readable

# F from r to w using the matrix inversion functionality of numpy
print ("(Frame Transform) F from r to w is the inverse which is the following 4x4 matrix:" )
frame_transform_r_w = np.linalg.inv(frame_transform_w_r) # using numpy matrix inversion
print(frame_transform_r_w)
print() # add a blank line to make it more readable

homogeneous_transform_w_r = frame_transform_r_w
homogeneous_transform_r_w = frame_transform_w_r
    
# q coords is r coords rotated about z by 90 degrees
frame_transform_r_q = ht.degreesRotZ(90)
print ("(Frame Transform) F from r to q is the inverse which is the following 4x4 matrix:" )
print(frame_transform_r_q)
print() # add a blank line to make it more readable


p1_world = ht.makePoint(0,0,0)
p1_robot = ht.makePoint(-10,0,0)

p2_world = ht.makePoint(3.5, 0, -1.5)
p2_robot = ht.makePoint(-6.5, 0, -1.5)


for tempPair in ((p1_world, "p1_world"), (p1_robot, "p1_robot"), (p2_world, "p2_world"), (p2_robot, "p2_robot")):
    print ("\n" + tempPair[1]+":")
    print (tempPair[0])


p1_from_world_to_robot = np.matmul(homogeneous_transform_w_r, p1_world)
if np.array_equal(p1_from_world_to_robot, p1_robot):
    print("Yay! Multiplication worked for point p1")
else:
    print("************* Problem multiplication did NOT work for point p1")
        
        
p2_from_robot_to_world = np.matmul(homogeneous_transform_r_w, p2_robot)
if np.array_equal(p2_from_robot_to_world, p2_world):
    print("Yay! Multiplication worked for point p2")
else:
    print("************* Problem multiplication did NOT work for point p2")


(Frame Transform) F from w to r is Trans (10, 0, 0) which is the following 4x4 matrix:
[[1.000 0.000 0.000 10.000]
 [0.000 1.000 0.000 0.000]
 [0.000 0.000 1.000 0.000]
 [0.000 0.000 0.000 1.000]]

(Frame Transform) F from r to w is the inverse which is the following 4x4 matrix:
[[1.000 0.000 0.000 -10.000]
 [0.000 1.000 0.000 0.000]
 [0.000 0.000 1.000 0.000]
 [0.000 0.000 0.000 1.000]]

(Frame Transform) F from r to q is the inverse which is the following 4x4 matrix:
[[0.000 -1.000 0.000 0.000]
 [1.000 0.000 0.000 0.000]
 [0.000 0.000 1.000 0.000]
 [0.000 0.000 0.000 1.000]]


p1_world:
[[0]
 [0]
 [0]
 [1]]

p1_robot:
[[-10]
 [  0]
 [  0]
 [  1]]

p2_world:
[[3.500]
 [0.000]
 [-1.500]
 [1.000]]

p2_robot:
[[-6.500]
 [0.000]
 [-1.500]
 [1.000]]
Yay! Multiplication worked for point p1
Yay! Multiplication worked for point p2
